//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ord_id { get; set; }
        public Nullable<int> ord_fk_product { get; set; }
        public Nullable<int> ord_fk_invoice { get; set; }
        public Nullable<System.DateTime> ord_date { get; set; }
        public Nullable<int> ord_qty { get; set; }
        public Nullable<double> ord_bill { get; set; }
        public Nullable<int> ord_unitprice { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
    }
}
